### ISSUE TITLE
Tracker

### ISSUE THREAD

**Issue by mark-omarov** [mark-omarov/larky-link#5]
- Shorten URL
  - UI
    - [x] #15
    - [x] #18
        - [x] #24
    - [x] #19
  - Database
    - [x] Table to store original URLs and their corresponding shortened codes
    - [x] #12

- URL redirection
  - API
    - [x] Endpoint to handle redirection from shortened to original URL
  - Database
    - [x] Quick lookup for mapping shortened codes to original URLs

- Security
  - API
    - [x] #21
    - [ ] CAPTCHA ?

- Application analytics
  - [x] #22

**Comment by mark-omarov** [comment]
Unauthenticated users to posses session ulid for data association. That's not good enough for abuse prevention, but in combination with rate limit that should be good enough for now.
